model:
  policy: "MultiInputPolicy"
  batch_size: 2048
  n_steps: 64
  learning_rate: 0.0001
  n_epochs: 10
  clip_range: 0.2
  vf_coef: 0.5
  ent_coef: 0.01
  gamma: 0.99
  gae_lambda: 0.95
  max_grad_norm: 0.5
  verbose: 1

training:
  num_obstacles: 150
  model_inputs: ["depth"] # This should be a non-empty subset of ["velocity", "reverse", "history", "depth/point_cloud"]
  total_timesteps: 1000000
  num_envs: 32
  device: "cuda" # "cpu" for CPU