model:
  policy: "MultiInputPolicy"
  batch_size: 64
  learning_rate: 0.0003
  buffer_size: 1000000
  learning_starts: 1000
  train_freq: 1
  gradient_steps: 1
  ent_coef: "auto"
  target_update_interval: 1
  gamma: 0.99
  tau: 0.005
  verbose: 1

training:
  num_obstacles: 120
  model_inputs: ["depth", "velocity"] # This should be a non-empty subset of ["velocity", "reverse", "depth/point_cloud"]
  total_timesteps: 100000
  num_envs: 8
  device: "cuda" # "cpu" for CPU