model:
  policy: "MultiInputPolicy"
  batch_size: 256
  learning_rate: 0.0003
  buffer_size: 10000
  learning_starts: 1000
  train_freq: 1
  gradient_steps: 1
  ent_coef: "auto"
  target_update_interval: 1
  gamma: 0.99
  tau: 0.005
  verbose: 1

training:
  num_obstacles: 150
  model_inputs: ["depth","history","velocity"] # This should be a non-empty subset of ["pose", "velocity", "steering", "depth"]
  total_timesteps: 100000
  num_envs: 1
  device: "cuda" # Change to "cuda" for Nvidia or "cpu" for CPU